### ISSUE TITLE
Feature request - Multiple pass

### ISSUE THREAD

**Issue by mothra78** [mrbeam/mrbeam-inkscape-ext#3]
Hi, 

Would be great if you could add in the advanced settings the number of passes (default 1) to generate Gcode with multiple passes for cutting (wood)

**Comment by hungerpirat** [comment]
Thanks for reporting this. It is on our list. See as well
https://github.com/mrbeam/OctoPrint/issues/34

Best,
Teja

**Comment by mrbeam** [comment]
implemented!
